server.port=8081
# H2
spring.datasource.url=jdbc:h2:file:./data/testdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=none

# flyway
spring.flyway.enabled=true
spring.flyway.locations=filesystem:./data/migration


# logging SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.transaction=DEBUG

logging.level.org.springframework=INFO
logging.level.com.vaadin=DEBUG

# Secret key (JwtTokenUtils)
jwt.secret=9fac224c5f6dadd37d3f8b8b40513740c12f24e98db4db94fb86ccf3f0311b0b5085e2e057a69572618aa648852a5cddb44c9746036c943f93760d7fc3de61ad
jwt.expiration=3600

# Values for IP-block (LoginAttemptService)
security.login.max-attempts=5
security.login.block_time_in_minutes=15
security.login.clear_old_entities=1
security.login.time_for_save_ip=1
security.login.capthca_count=2

# Values for authorization block (AccountSecurityService)
security.account.max_failed_attempts=3
security.account.lock_duration_hours=1
security.account.capthca_count=2

recaptcha.secret=6LcrPtErAAAAAErsEtUmCEa8p1aqxwkBuU9ST8QZ