# PostgreSQL
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop

# logging SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.transaction=DEBUG

logging.level.org.springframework=INFO
logging.level.com.vaadin=DEBUG

# Secret key (JwtTokenUtils)
jwt.secret=9fac224c5f6dadd37d3f8b8b40513740c12f24e98db4db94fb86ccf3f0311b0b5085e2e057a69572618aa648852a5cddb44c9746036c943f93760d7fc3de61ad
jwt.expiration=604800000