users.path = http://localhost:8081/api/users
register.path = http://localhost:8081/api/register
auth.path = http://localhost:8081/api/api/auth

# Captcha logic
recaptcha.secret=6LcrPtErAAAAAErsEtUmCEa8p1aqxwkBuU9ST8QZ
recaptcha.site_key=6LcrPtErAAAAAKJC3Ldraf20w800GW4KgZu5srBE